In [2]:
import numpy as np 
import cv2
import imutils


In [3]:
cap = cv2.VideoCapture("/home/roar/Desktop/ROARLaneDetection/training_1000.MOV")
cap.isOpened()

[mov,mp4,m4a,3gp,3g2,mj2 @ 0x55d4c370a100] Referenced QT chapter track not found


True

In [18]:
while True:
    ret,frame = cap.read()
    if not ret:
        break
    img_hsv = cv2.cvtColor(frame, cv2.COLOR_RGB2HSV)
    frame = cv2.GaussianBlur(frame, (5,5), 0)
    
    # cv2.imshow('image',blur)
    # key = cv2.waitKey(1) & 0xFF
    # if key == ord('q'):
    #     cv2.destroyAllWindows()
    #     break
    # continue


    #frame = imutils.resize(frame,width = 960)
    seed = (1079, 960)

    box = (200, 200)
    x = (seed[0] - box[0] - box[1], seed[0])
    y = (seed[1] - box[1], seed[1] + box[1])


    mean = np.mean(frame[x[0]:x[1], y[0]:y[1], :], axis = (0,1))
    std = np.std(frame[x[0]:x[1], y[0]:y[1], :], axis = (0,1))
    scale = 2.5
    scale_std = std * scale
    print(scale_std)
    # break
    # scale_std = [200, 20, 200]
    # print(mean, '/n',std)

    frame[seed[0], seed[1]] = mean
    print(frame.shape)

    #crop_frame = frame[200:]
    #print(crop_frame.shape)

    cv2.floodFill(frame, None, seedPoint=seed, newVal=(0, 0, 255), \
        loDiff=tuple(scale_std), upDiff=tuple(scale_std), flags= cv2.FLOODFILL_FIXED_RANGE)
    cv2.circle(frame, seed, 2, (0, 255, 0), cv2.FILLED, cv2.LINE_AA)

    #cv2.floodFill(frame, None, seedPoint=(670, 960), newVal=(0, 0, 255), loDiff=tuple(scale_std), upDiff=tuple(scale_std), flags= cv2.FLOODFILL_FIXED_RANGE)
    #cv2.circle(frame, seed, 2, (0, 255, 0), cv2.FILLED, cv2.LINE_AA);

    cv2.imshow('image',frame)
    key = cv2.waitKey(1) & 0xFF
    if key == ord('q'):
        cv2.destroyAllWindows()
        break

[21.65310186 21.68631688 21.95102683]
(1080, 1920, 3)
[21.65631008 21.7033159  21.97293122]
(1080, 1920, 3)
[21.17509143 20.93159521 21.40798317]
(1080, 1920, 3)
[20.24597162 20.23246583 20.50047376]
(1080, 1920, 3)
[22.12462968 22.16657455 22.395051  ]
(1080, 1920, 3)
[22.97153343 22.9787273  23.25668936]
(1080, 1920, 3)
[22.24740671 22.41186576 22.48812501]
(1080, 1920, 3)
[21.39390752 21.72905701 21.6311946 ]
(1080, 1920, 3)
[21.29710902 21.35787924 21.4153596 ]
(1080, 1920, 3)
[22.27284838 22.6717663  22.51230391]
(1080, 1920, 3)
[23.92008847 24.07191321 24.04684096]
(1080, 1920, 3)
[20.37301777 20.79521155 20.63069039]
(1080, 1920, 3)
[22.68843914 22.92602403 22.93445488]
(1080, 1920, 3)
[23.28109459 23.47332397 23.50600413]
(1080, 1920, 3)
[19.94335603 20.09896306 20.14522731]
(1080, 1920, 3)
[21.88631545 21.86996568 22.02499993]
(1080, 1920, 3)
[19.31338344 19.46533339 19.56048303]
(1080, 1920, 3)
[22.29117786 22.20818049 22.40458079]
(1080, 1920, 3)
[23.07518454 23.06659521 23.